server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:  
          uri: https://github.com/rollingstoneecomm/rollingstone-ecommerce-remote-config-repository 
          searchPaths: [project name],[project name] 
          username: rollingstonecomm
          password:  KeepLearning$$1
  
  